version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        environment:
          TEST_DATABASE_URL: postgresql://ubuntu@localhost/circle_t?sslmode=disable
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
      - image: circleci/postgres:9.6.5-alpine-ram
    steps:
      - checkout
      - run: sudo apt install postgresql-client-9.6
      - run: pg_isready -d $TEST_DATABASE_URL
      - run: whoami
